language: node_js
node_js:
  - "8"
  - "10"
  - "12"

cache:
  yarn: true

jobs:
  include:
    - stage: Test
      name: Unit Tests
      install:
        - yarn --frozen-lockfile
      script:
        - yarn test --coverage
      after_script:
        # Push tests coverage data to Coveralls:
        - ./node_modules/.bin/coveralls < ./coverage/lcov.info

notifications:
  email:
    on_failure: change
    on_success: never
